### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by 031nna** [Metumaribe/filesharerChrome#1]
We need to find a logo to replace 'LOGO'

**Comment by 031nna** [comment]
@bitruspikin ^

**Comment by crvftsmvn** [comment]
Ok, will figure something out over the weekend, should have something by Monday

**Comment by 031nna** [comment]
Ok, sounds good. I was unable to get to the chrome files, i was working on a clients work, will look into it tonight and submit soonest.

**Comment by crvftsmvn** [comment]
I have a Logo
